#pragma once

#include <cstdint>
#include <memory>
#include <mutex>
#include <random>
#include <vector>

namespace cudaforge::scheduler {

/*
    Configuration parameters for speculative decoding execution.
 */
struct SpeculativeConfig {
  size_t gamma = 5; // Number of lookahead draft tokens per speculative step (K)
  float temperature = 1.0f; // Sampling temperature
  float top_p = 1.0f;       // Top-p (nucleus) threshold
  uint64_t rng_seed = 42;   // Random seed for verification sampling
};

/*
    Container holding the outcome of a single parallel verification step.
 */
struct SpeculativeVerificationResult {
  std::vector<int32_t>
      accepted_tokens; // Verified tokens accepted by the Target model
  int32_t
      final_token; // Corrected token sampled on first rejection or bonus token
  size_t num_accepted = 0;      // Count of accepted draft tokens
  bool end_of_sequence = false; // Flag indicating if EOS token was encountered
};

/*
    Speculative Engine performing lookahead candidate verification and rejection
   sampling.
 */
class SpeculativeEngine {
public:
  explicit SpeculativeEngine(const SpeculativeConfig &config);
  ~SpeculativeEngine() = default;

  /**
   * @brief Performs parallel rejection sampling verification over draft
   * candidates.
   *
   * @param draft_tokens Vector of K candidate token IDs generated by the draft
   * model.
   * @param draft_probs Vector of probability distributions (size K x
   * vocab_size) from draft model.
   * @param target_probs Vector of probability distributions (size (K+1) x
   * vocab_size) from target model.
   * @param eos_token_id End-of-sequence token ID.
   * @return SpeculativeVerificationResult verified acceptance and corrected
   * output sequence.
   */
  SpeculativeVerificationResult
  verify_candidates(const std::vector<int32_t> &draft_tokens,
                    const std::vector<std::vector<float>> &draft_probs,
                    const std::vector<std::vector<float>> &target_probs,
                    int32_t eos_token_id);

  /**
   * @brief Greedy verification path for zero-temperature decoding.
   */
  SpeculativeVerificationResult
  verify_candidates_greedy(const std::vector<int32_t> &draft_tokens,
                           const std::vector<std::vector<float>> &target_probs,
                           int32_t eos_token_id);

  void set_config(const SpeculativeConfig &config) {
    std::lock_guard<std::mutex> lock(engine_mutex_);
    config_ = config;
  }

  SpeculativeConfig get_config() const {
    std::lock_guard<std::mutex> lock(engine_mutex_);
    return config_;
  }

private:
  SpeculativeConfig config_;
  mutable std::mutex engine_mutex_;
  std::mt19937 rng_;

  int32_t sample_from_distribution(const std::vector<float> &probs);
  int32_t sample_adjusted_distribution(const std::vector<float> &target_p,
                                       const std::vector<float> &draft_q);
};

} // namespace cudaforge::scheduler