import time
from typing import Callable, Any
from prometheus_client import (
    Counter,
    Gauge,
    Histogram,
    Summary,
    CollectorRegistry,
    REGISTRY,
)

# Custom Registry or Global REGISTRY
registry: CollectorRegistry = REGISTRY

# Latency Histograms
HTTP_REQUEST_LATENCY_SECONDS = Histogram(
    "cudaforge_http_request_latency_seconds",
    "HTTP Request processing latency in seconds",
    ["endpoint", "status"],
    buckets=(0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1.0, 2.5, 5.0, 10.0),
    registry=registry,
)

TIME_TO_FIRST_TOKEN_SECONDS = Histogram(
    "cudaforge_ttft_seconds",
    "Time to First Token (TTFT) latency in seconds",
    ["model_name", "precision"],
    buckets=(0.002, 0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1.0, 2.5),
    registry=registry,
)

INTER_TOKEN_LATENCY_SECONDS = Histogram(
    "cudaforge_itl_seconds",
    "Inter-Token Latency (ITL) between generated tokens in seconds",
    ["model_name", "precision"],
    buckets=(0.001, 0.002, 0.005, 0.01, 0.02, 0.05, 0.1),
    registry=registry,
)

# Throughput Counters
GENERATED_TOKENS_TOTAL = Counter(
    "cudaforge_generated_tokens_total",
    "Total tokens generated by the inference engine",
    ["model_name", "precision", "phase"],  # phase: prefill vs decode
    registry=registry,
)

PROMPT_TOKENS_TOTAL = Counter(
    "cudaforge_prompt_tokens_total",
    "Total prompt tokens ingested",
    ["model_name"],
    registry=registry,
)

INFERENCE_REQUESTS_TOTAL = Counter(
    "cudaforge_requests_total",
    "Total inference requests handled",
    ["status", "stop_reason"],
    registry=registry,
)

# Engine & Memory Gauges (Low-Level Systems Telemetry)
KV_CACHE_USAGE_RATIO = Gauge(
    "cudaforge_kv_cache_usage_ratio",
    "Current KV-cache block allocation usage ratio (0.0 to 1.0)",
    ["device_id"],
    registry=registry,
)

GPU_MEMORY_UTILIZATION_BYTES = Gauge(
    "cudaforge_gpu_memory_bytes",
    "GPU Memory consumption in bytes",
    ["device_id", "category"],  # category: weights, kv_cache, activations, workspace
    registry=registry,
)

ACTIVE_RUNNING_REQUESTS = Gauge(
    "cudaforge_active_requests",
    "Number of currently active requests in the continuous batching scheduler",
    registry=registry,
)

WAITING_QUEUE_LENGTH = Gauge(
    "cudaforge_waiting_queue_length",
    "Number of requests waiting in scheduler admission queue",
    registry=registry,
)

KERNEL_DISPATCH_TIME_MICROSECONDS = Summary(
    "cudaforge_kernel_dispatch_us",
    "Kernel dispatch overhead in microseconds",
    ["kernel_name", "backend"],  # backend: cuda vs triton
    registry=registry,
)


def trace_kernel_execution(kernel_name: str, backend: str = "cuda") -> Callable:
    """Decorator to measure low-level kernel execution or dispatch timing."""
    def decorator(func: Callable) -> Callable:
        def wrapper(*args: Any, **kwargs: Any) -> Any:
            start = time.perf_counter_ns()
            res = func(*args, **kwargs)
            duration_us = (time.perf_counter_ns() - start) / 1000.0
            KERNEL_DISPATCH_TIME_MICROSECONDS.labels(
                kernel_name=kernel_name, backend=backend
            ).observe(duration_us)
            return res
        return wrapper
    return decorator


__all__ = [
    "HTTP_REQUEST_LATENCY_SECONDS",
    "TIME_TO_FIRST_TOKEN_SECONDS",
    "INTER_TOKEN_LATENCY_SECONDS",
    "GENERATED_TOKENS_TOTAL",
    "PROMPT_TOKENS_TOTAL",
    "INFERENCE_REQUESTS_TOTAL",
    "KV_CACHE_USAGE_RATIO",
    "GPU_MEMORY_UTILIZATION_BYTES",
    "ACTIVE_RUNNING_REQUESTS",
    "WAITING_QUEUE_LENGTH",
    "KERNEL_DISPATCH_TIME_MICROSECONDS",
    "trace_kernel_execution",
]